import Header from "./components/Header";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <main className="container max-w-screen-xl min-h-screen mx-auto px-4">
                <Header />
                {children}
            </main>
        </html>
    );
}
